packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

disallowWorkspaceCycles: true
engineStrict: true
injectWorkspacePackages: true
saveExact: true
strictPeerDependencies: true

peerDependencyRules:
  allowedVersions:
    typescript: 6.0.3

syncInjectedDepsAfterScripts:
  - build
